### ISSUE TITLE
V2.0 appimage missing libgtk-4

### ISSUE THREAD

**Issue by jocutajar** [gdm-settings/gdm-settings#137]
### What happened?

Hey, thanks for improving the lack of GDM configuration.

I've just downloaded the appimage release [2.0](https://github.com/realmazharhussain/gdm-settings/releases/tag/v2.0)

```
$ Login_Manager_Settings.AppImage 

** (process:41008): WARNING **: 16:56:36.600: Failed to load shared library 'libgtk-4.so.1' referenced by the typelib: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_Login_UZKtIt/usr/lib/libicuuc.so.72)
Traceback (most recent call last):
  File "/tmp/.mount_Login_UZKtIt/usr/bin/gdm-settings", line 27, in <module>
    from gdm_settings import Application
  File "/tmp/.mount_Login_UZKtIt/usr/lib/python3.10/site-packages/gdm_settings/__init__.py", line 1, in <module>
    from .app import Application
  File "/tmp/.mount_Login_UZKtIt/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 10, in <module>
    from gi.repository import Adw, Gtk
```

### Expected behavior

I think the point of an appimage is indeed that it brings with it all dependencies. Should not fail on missing libs.

### To Reproduce

Just run the appimage on a system that doesn't have libgtk-4 , here debian 11.

### Application Version

2.0

### Format/Source

AppImage

### Environment

- **OS**: Debian 11
- **GNOME**: 3.38

**Comment by realmazharhussain** [comment]
Try running [this](https://mega.nz/file/PoNwQbiT#3n1JIY2_pRwEcw0aLF37Db--iiHW86iz-tcovFlWkqQ) AppImage and tell me if it works.

**Comment by dik23** [comment]
> Try running [this](https://mega.nz/file/PoNwQbiT#3n1JIY2_pRwEcw0aLF37Db--iiHW86iz-tcovFlWkqQ) AppImage and tell me if it works.

(AppImageLauncher:29309): GLib-CRITICAL **: 18:58:12.248: g_file_test: assertion 'filename != NULL' failed
/usr/bin/env: symbol lookup error: /tmp/.mount_Login_YQjqMT/usr/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE

**Comment by realmazharhussain** [comment]
What about this one?

https://mega.nz/file/Wk8HCQ7R#qYwjoZB7twbACzlYmF2iSQ4QIrsAdX4mWH7KmLfZajs

**Comment by dik23** [comment]
`(AppImageLauncher:79642): GLib-CRITICAL **: 13:04:46.854: g_file_test: assertion 'filename != NULL' failed
python3: symbol lookup error: /tmp/.mount_Login_jTmskZ/usr/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE`

**Comment by realmazharhussain** [comment]
- Try running it from the commandline with `--appimage-mount` option. This should mount the AppImage as a disk image and print out path of the directory it was mounted to.
- Copy the output
- Then, open a new terminal window (or tab) and paste previously copied path and add `/AppRun` to the end of it.
  As a result of this, your command should look something like `/tmp/.mount_Login_SANvcv/AppRun`.
- Execute the command
- Tell me what happens

**Comment by dik23** [comment]
> ./Login_Manager_Settings\ \(1\).AppImage --appimage-mount
> /tmp/.mount_Login_dSQgF9

> /tmp/.mount_Login_dSQgF9/AppRun
> <pre>python3: symbol lookup error: /tmp/.mount_Login_dSQgF9/usr/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE</pre>

> /tmp/.mount_Login_dSQgF9
> ^C
> $

**Comment by realmazharhussain** [comment]
It seems like a lot of similar bug reports are caused due to GLibC. I should have communicated earlier about this, but I am working on making the app buildable on older systems so that an sensible AppImage without GLibC could be created.

It will take some time however.

**Comment by realmazharhussain** [comment]
Well, that didn't happen!

Also, the plan has now changed. Going forward, the plan is to bundle everything, turning the AppImage into something of [a Zero Dependency Appliction](https://zapps.app/) where it does not depend on system libraries at all and uses only what has been bundled with it, fixing all the issues caused by mismatching library version.

**Comment by atmadeep** [comment]
Hi @realmazharhussain, On Ubuntu 20.04 (GDM), receiving a similar error:
`/usr/bin/env: symbol lookup error: /tmp/.mount_GDM_Se9GhcdF/usr/lib/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE `

When running it as an appimage using : `./GDM_Settings.AppImage`
However, when using: `./GDM_Settings.AppImage --appimage-mount`, then the process is stuck at:
`/tmp/.mount_GDM_SenQHIfq`

**Comment by realmazharhussain** [comment]
> when using: `./GDM_Settings.AppImage --appimage-mount`, then the process is stuck at:
/tmp/.mount_GDM_SenQHIfq

The process is not stuck, this is how `--appimage-mount` works. You run it in the terminal, copy the line it prints out (it is the path at which AppImage is mounted). You can go to that path and do whatever. And when you're done, you press Ctrl+C at the terminal, which unmounts the AppImage.

**Comment by realmazharhussain** [comment]
This issue is being tracked in #209 now.
