### ISSUE TITLE
[BUG] Can't compile from source: Namespace Adw does not contain a type called EntryRow

### ISSUE THREAD

**Issue by mrmeszaros** [gdm-settings/gdm-settings#140]
### What happened?

I tried to compile from source, but got the message: `error: Namespace Adw does not contain a type called EntryRow`

### Expected behavior

A happy little build from source.

### To Reproduce

Follow the steps provided:

```
git clone --depth=1 https://github.com/realmazharhussain/gdm-settings
cd gdm-settings
meson setup build
meson install -C build
```

### Detailed Explanation (Optional)

This must be related to the closed issue #112 

Ubuntu 22.04 jammy does not have Adwaita at 1.2:

```
vagrant@ubuntu2204 ~/S/gdm-settings> apt show libadwaita-1-dev
Package: libadwaita-1-dev
Version: 1.1.0-1ubuntu2
...
```

### Application Version

2.0

### Format/Source

Source Code

### Environment

- **OS**:  Ubuntu 22.04
- **GNOME**: 42.5

**Comment by realmazharhussain** [comment]
> This must be related to the closed issue https://github.com/realmazharhussain/gdm-settings/issues/112

Yes, it is and I am working on making the app buildable on older systems but it will take quiet some time.

**Comment by realmazharhussain** [comment]
The plan has changed. I did initially try and make GDM Settings buildable on older systems but I'd have to make LibAdwaita, GTK, GLib, etc. buildable on older systems which is a very big/difficult task.

So now, the focus would be making an AppImage that actually works, turning the AppImage into something like [a Zapp][Zapps]. Along with that, there could also be an officially supported binary archive.

[Zapps]: https://zapps.app
