### ISSUE TITLE
Wallpaper setting not working properly

### ISSUE THREAD

**Issue by TadoTheMiner** [gdm-settings/gdm-settings#158]
### What happened?

When you set a different login screen background, on login screen it is on that wallpaper only for a second, then it returns to none. Also after logging, the screen is stuck on that wallpaper for something like three cseconds..

### Expected behavior

Login screen showing that wallpaper normally

### To Reproduce

1. Change the backgrount to a jpg image
2. Reboot the system

### Application Version

2.1

### Format/Source

Flatpak

### Environment

- **OS**: Fedora 38
- **GNOME**: 44

**Comment by realmazharhussain** [comment]
Does this happen with the shell theme too or just the background?

**Comment by sergiotca** [comment]
Same issue, same platform (Fedora 38, GNOME 44, Flatpack 2.1).

I'm not using any specific shell theme (other than "default") so I cannot add to this.

One interesting thing I've noticed though, even though the applied wallpaper fails to display, the Fedora logo that usually shows at the bottom of the screen is now missing. 

Also, weirdly enough, once I enter my password and press login, I can actually see the selected wallpaper for a split second before getting to the desktop. As if it had been in the back of the GDM UI the whole time. 
Same behaviour can be seen choosing a color as background instead of a picture.

Using the tool to reset to the default settings brings back the Fedora logo at the bottom, but strangely enough I can still see the last applied wallpaper for an instant after logging in.

BTW, I'm using wayland.

**Comment by realmazharhussain** [comment]
> I'm not using any specific shell theme (other than "default") so I cannot add to this.

The app modifies the shell theme in order to apply background and top bar tweaks. So, one way to test this would be to change for example topbar text & background colors.

**Comment by DanielsSt** [comment]
I have the same issue, also Gnome 44 on Fedora 38 and default theme.
The same behavior as described above - seeing image for a second or two then it fades to a single color ( I assume `#282828`) and fades back to the chosen image right after logging in. 
Same behavior when changing the background to a static color.

Seems like shell theme gets modified successfully, managed to change topbar colors with no issues.

Unfortunately I do not have that much experience of customizing themes and/or figuring out what happens in the login screen UI

**Comment by sergiotca** [comment]
> > I'm not using any specific shell theme (other than "default") so I cannot add to this.
> 
> The app modifies the shell theme in order to apply background and top bar tweaks. So, one way to test this would be to change (for example) topbar text & background colors.

I went ahead and changed the topbar text and background colors. 
They applied just fine (I used red on blue so it was pretty obvious):
![image](https://user-images.githubusercontent.com/41351896/231888461-80647047-64b2-4d0e-a51f-55eca2de8071.png)
I assume this means the shell theme is indeed being changed by this app. 

This is mere speculation, but the fact that you can see the applied wallpaper for a split second after logging in makes me wonder if Fedora 38 (or maybe Gnome 44) is not introducing a new element to GDM that sits in between the background and the logging dialog... 🤔

**Comment by mosK1T0** [comment]
I think I have the same issue. I'am also on Fedora 38 with Gnome 44. One my main monitor I see the same behavior. Fading out and than in for as second after login. But on my second monitor the background picture stays visible.

**Comment by sekurilabs** [comment]
I have the same issue (Ubuntu 23.04, Gnome 44). I can see the background image barely, like if a gray colored overlay was in front of the image with low opacity. For a split second before the desktop shows, I can see the background image without that "overlay". My suspicion is that gdm-settings is missing something from the new Gnome/GDM versions.

**Comment by realmazharhussain** [comment]
I don't have 44 yet. I'll work on this after Manjaro gets the 44 update and I have some time on my hands. I'll be busy for a couple of weeks.

@MichielP80 

> Is there another way to do this on the new Ubuntu Lunar Lobster?

This is a very new problem. So, I doubt there'll be any known solution to this right now. But I'm not too sure. I could be wrong.

**Comment by NeuHix** [comment]
I also have this same issue on F38.

**Comment by Loatchi** [comment]
I have the same problem on Gentoo.

I've tried to downgrade gdm to versions I know it should work (44 -> 43). It did not work. However downgrading gnome-shell worked.

I've opened an [issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6659) on gnome-shell gitlab.

Nor Gdm nor gnome-shell provides logs that says that there is an error loading a background of any kind. If you have meaningful informations you should share it on gnome-shell's gitlab !

**Comment by realmazharhussain** [comment]
> However downgrading gnome-shell worked.

That's because the UI for the login screen is part of GNOME Shell.

**Comment by rowlul** [comment]
Same on Arch Linux 6.3.1-zen1-1-zen, gdm 44.1-1, gnome-shell 1:44.1-3

**Comment by FNklazo** [comment]
I found a fix for this:
Install a theme to /usr/local/share/themes/
Change the shell theme to it in gdm-settings

Hopefully this works for someone else...

**Comment by FNklazo** [comment]
@NeuHix Well the theme I used is: `https://github.com/vinceliuice/Colloid-gtk-theme`

**Comment by NeuHix** [comment]
@realmazharhussain It works!

**Comment by Loatchi** [comment]
Here is a patch for the release 3.1 .
I'm using it for the Gentoo release on my overlay.

```
diff --git a/src/settings.py b/src/settings.py
index 7857872..9d1e534 100644
--- a/src/settings.py
+++ b/src/settings.py
@@ -240,6 +240,7 @@ class SettingsManager (GObject.Object):
         background_image = appearance_settings['background-image']
         if background_type is BackgroundType.image and background_image:
             css += "\n"
+            css += ".login-dialog,\n"
             css += "#lockDialogGroup {\n"
             css += "  background-image: url('resource:///org/gnome/shell/theme/background');\n"
             css += "  background-size: cover;\n"
```
(For some reasons, Github did not allow me to attach it)

Thanks @realmazharhussain !

**Comment by Tuxman2** [comment]
Hello,

The last Appimage file you given in the link don't work for me. I've got a core dump on Manjaro with Gnome 43.x. Can you update 3.1 release with the fix (Appimage, AUR package) ?

Thanks.

**Comment by realmazharhussain** [comment]
I will soon release version 3.2 with the fix.

Sadly there are a lot of issues with the AppImage and the AppImage of 3.2 release will probably also not work on your system.

I'm going to merge the fix into main now. After which, you'll be able to use `gdm-settings-git` package from the AUR with the fix.
