### ISSUE TITLE
Gnome 44 fades login image to grey in F38

### ISSUE THREAD

**Issue by jeffreywgh** [gdm-settings/gdm-settings#162]
### What happened?

When Fedora 38 starts up, login wallpaper is displayed fora short period before fading to grey with the login interface.  Interface otherwise function normally.

### Expected behavior

Login should fade in the wallpaper with the login UI, then fade out upon successful login.  

### To Reproduce

On a GNOME 44 installation, set background image to a jpg, then log out or restart.  Observe wallpaper during login process.

### Detailed Explanation (Optional)

My suspicion is that the gresource for the gnome-shell-theme has changed behavior and the app needs to be updated to follow suit.

### Application Version

Likely Any

### Format/Source

Flatpak

### Environment

- **OS**:  Fedora 38
- **GNOME**:  44.0

**Comment by realmazharhussain** [comment]
This has already been reported and is being discussed in #158.
