### ISSUE TITLE
Error executing command as another user: Not authorized when running app on Arch

### ISSUE THREAD

**Issue by eguiraud** [gdm-settings/gdm-settings#163]
### What happened?

Running on Arch Linux, GDM display manager, sway window manager, inserting the correct root password after clicking "apply" still results in a permission denied:

```
~ gdm-settings -v
INFO: Application Version    = 3.1
INFO: Operating System       = Arch Linux
INFO: PackageType            = Unknown
INFO: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = None
INFO: pkexec version 122
INFO: Backing up default shell theme …
INFO: Applying GResource settings for generic system …
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/run/user/1000/app/io.github.realmazharhussain.GdmSettings/run-elevated' as the super user
Authenticating as: root
Password:
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
```

### Expected behavior

Inserting the root user password to escalate privileges should work.

### To Reproduce

Trying to change the background image, clicking "apply".

### Application Version

3.1

### Format/Source

AUR (gdm-settings)

### Environment

- **OS**: Arch
- **GNOME**: GDM 44.1

**Comment by realmazharhussain** [comment]
Sorry, this is an issue with Polkit itself. See [this video](https://www.youtube.com/watch?v=_O7l4co_F4k) from Brodie Robertson to learn more about this (including how to solve the issue).

**Comment by YuChuXi** [comment]
`sudo -E` maby useful
