### ISSUE TITLE
Unable to install on OpenSuSE Leap 15.5.

### ISSUE THREAD

**Issue by linxpatrick** [gdm-settings/gdm-settings#167]
### Description

Tried to install gdm-settings on OpenSuSE Leap 15.5 manually and with flatpak. Both methods failed stating glib-2.0 not found but there is a glib-2.x version installed by default. Can the utility be made to compile on OpenSuSE Leap 15 or can it be added to a repository that's available to OpenSuSE Leap 15 so it can be installed with zypper?

**Comment by realmazharhussain** [comment]
This is too little information to work with. Please! Fill a proper bug report.

> Both methods failed stating glib-2.0 not found

How did it state "glib-2.0 not found"? Include that in the bug report as well.
