### ISSUE TITLE
List themes and cursors on /root.

### ISSUE THREAD

**Issue by AligatorRicardo** [gdm-settings/gdm-settings#169]
### Description

In the current version, GDM Settings only list themes installed on /usr/share/ since GDM can't read files on user's home folder. However, I use Fedora Silverblue (an immutable distro) and this folder cannot be normally acessed but it is still possible to write in /root. 

### Explanation

Because of this  i suggest, if it is possible, to allow GDM Settings to see files from /root and not only from /usr/share.

**Comment by realmazharhussain** [comment]
Like you said,

> GDM can't read files on user's home folder.

`/root` is **root** user's home folder and even less accessible than any other user's home folder. No one can access it but the root user itself.

The actual solution is to use `/usr/local/share`. It is accessible to every user on the system and should be writable by privileged users (e.g. root) even on immutable distros.
