### ISSUE TITLE
Login Manager Flatpak on Immutable System 

### ISSUE THREAD

**Issue by Raul1198** [gdm-settings/gdm-settings#172]
### What happened?

I was try out immutable distribution like Fedora Silverblue & openSUSE Aeon(Micro Os Desktop GNOME)  running on GNOME Box  on my Fedora 38 Workstation(host) where in I was able to successfully use Login Manager Flatpak to configure GDM on Fedora Silverblue but on openSUSE Aeon it failed to configure GDM settings it show "Fail to Apply Settings" after authentication 

### Expected behavior

Successful changed login settings GDM on openSUSE Aeon

### To Reproduce

1. Install Login Manager from GNOME Software 
2. Launch Login Manager
3. Tweak you preferred settings
4. Hit Apply 

### Application Version

3.2

### Format/Source

Flatpak

### Environment

- **OS**: openSUSE Aeon (formally known as Micro Os Desktop based on openSUSE Tumbleweed)
- **GNOME**: 44.2

**Comment by realmazharhussain** [comment]
This is probably because `/etc` is read-only on openSUSE Aeon.

**Comment by realmazharhussain** [comment]
gdm-settings requires write access to `/etc` to function. As far as my understanding goes, there is nothing I can do about it. Sorry.

**Comment by realmazharhussain** [comment]
So, I read the wiki articles you linked and if I understand correctly, `/etc` **is** writable. So, it might be some other issue.

**Comment by realmazharhussain** [comment]
@Raul1198 If you are still here, can you provide the output of `io.github.realmazharhussain.GdmSettings -v` command?

**Comment by Raul1198** [comment]
should the above command be run as `flatpak run io.github.realmazharhussain.GdmSettings -v` if so here is the output, i t opened login manager and then i pressed apply followed by a sudo password promptand which failed 


```
bruce@localhost:~> flatpak run io.github.realmazharhussain.GdmSettings -v
INFO: Application Version    = 3.3
INFO: Operating System       = openSUSE MicroOS
INFO: PackageType            = Flatpak
INFO: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = None
INFO: pkexec version 121
INFO: Backing up default shell theme \u2026
INFO: Applying GResource settings for generic system \u2026
Error executing /run/user/1000/app/io.github.realmazharhussain.GdmSettings/run-elevated: Permission denied
```

**Comment by realmazharhussain** [comment]
Does pkexec work with other commands? Try running `pkexec sh` comand.

> should the above command be run as flatpak run io.github.realmazharhussain.GdmSettings -v

It is the same thing. Flatpak exports scripts that run the app, with the same filename as the app ids. So, you don't have to type `flatpak run` to run a flatpak.

**Comment by Raul1198** [comment]
i ran  `pkexec sh io.github.realmazharhussain.GdmSettings -v`  

```
bruce@localhost:~> pkexec sh io.github.realmazharhussain.GdmSettings -v
/usr/bin/sh: io.github.realmazharhussain.GdmSettings: No such file or directory
```



> Does pkexec work with other commands? Try running `pkexec sh` comand.
> 
> > should the above command be run as flatpak run io.github.realmazharhussain.GdmSettings -v
> 
> It is the same thing. Flatpak exports scripts that run the app, with the same filename as the app ids. So, you don't have to type `flatpak run` to run a flatpak.

so if i run io.github.realmazharhussain.GdmSettings -v should launch login manager bruce@localhost:~> io.github.realmazharhussain.GdmSettings -v
bash: io.github.realmazharhussain.GdmSettings: command not found



i ran  `pkexec sh io.github.realmazharhussain.GdmSettings -v`  

```
bruce@localhost:~> pkexec sh io.github.realmazharhussain.GdmSettings -v
/usr/bin/sh: io.github.realmazharhussain.GdmSettings: No such file or directory
```

**Comment by realmazharhussain** [comment]
> so if i run io.github.realmazharhussain.GdmSettings -v should launch login manager

Yes.

> `bruce@localhost:~> pkexec sh io.github.realmazharhussain.GdmSettings -v`

The command was supposed to be just `pkexec sh`, not `pkexec sh io.github.realmazharhussain.GdmSettings -v`. Anyway, `pkexec sh io.github.realmazharhussain.GdmSettings -v` was also helpful.

So, now we need to test if pkexec runs other user-made scripts or not. That can be done with the following steps.

1. Write a new file as `/run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script` with the contents `#!/bin/sh` by running the command
 
   ```bash
   echo '#!/bin/sh' | sudo tee /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script
   ```

1. Make the script executable

   ```bash
   sudo chmod +x /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script
   ```

1. Run the script with pkexec

   ```bash
   pkexec /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script
   ```

**Comment by Raul1198** [comment]
so tried using `pkexec` and then `io.github.realmazharhussain.GdmSettings -v` here is the output   

```
bruce@localhost:~> pkexec sh
sh-5.2# io.github.realmazharhussain.GdmSettings -v
sh: io.github.realmazharhussain.GdmSettings: command not found
```


from the looks of the output the command doesn't works 

here it the output  
```
bruce@localhost:~> echo '#!/bin/sh' | sudo tee /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script
[sudo] password for root: 
tee: /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script: No such file or directory
#!/bin/sh
```

**Comment by realmazharhussain** [comment]
Run `mkdir -p /run/user/1000/app/io.github.realmazharhussain.GdmSettings/` and then try the app again.

**Comment by Raul1198** [comment]
here it output after mkdir 

```
bruce@localhost:~> mkdir -p /run/user/1000/app/io.github.realmazharhussain.GdmSettings/
bruce@localhost:~> echo '#!/bin/sh' | sudo tee /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script
[sudo] password for root: 
#!/bin/sh
bruce@localhost:~> sudo chmod +x /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script
bruce@localhost:~> pkexec /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script
Error executing /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script: Permission denied
```

**Comment by realmazharhussain** [comment]
Does it work if you copy the script to somewhere else e.g. $HOME.

```bash
cp /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script -t ~
pkexec ~/custom-script
```

**Comment by Raul1198** [comment]
yes in home folder there a custom-script file with contnt being `#!/bin/sh`

**Comment by realmazharhussain** [comment]
No, I mean, is pkexec able to run it without Permission Error?

**Comment by Raul1198** [comment]
yes it is completed without error

```
bruce@localhost:~> cp /run/user/1000/app/io.github.realmazharhussain.GdmSettings/custom-script -t ~
bruce@localhost:~> pkexec ~/custom-script
bruce@localhost:~>
```

**Comment by realmazharhussain** [comment]
What is the output of

```bash
ls -ld /run/user/1000/app/io.github.realmazharhussain.GdmSettings
ls -ld /run/user/1000/app
ls -ld /run/user/1000
ls -ld /run/user
ls -ld /run
```

**Comment by Raul1198** [comment]
```
bruce@localhost:~> ls -ld /run/user/1000/app/io.github.realmazharhussain.GdmSettings
drwxr-xr-x. 4 bruce bruce 180 Aug 27 16:31 /run/user/1000/app/io.github.realmazharhussain.GdmSettings
bruce@localhost:~> ls -ld /run/user/1000/app
drwxr-xr-x. 4 bruce bruce 80 Aug 27 16:38 /run/user/1000/app
bruce@localhost:~> ls -ld /run/user/1000
drwx------. 17 bruce bruce 500 Aug 27 16:31 /run/user/1000
bruce@localhost:~> ls -ld /run/user
drwxr-xr-x. 3 root root 60 Aug 27 16:30 /run/user
bruce@localhost:~> ls -ld /run
drwxr-xr-x. 37 root root 880 Aug 27 16:48 /run
```

**Comment by Raul1198** [comment]
There are support groups wherein openSUSE Aeon devs are mostly active, they can give more help and detailed insight on internal working of Aeon 
[openSUSE Aeon Page](https://en.opensuse.org/Portal:Aeon#Place_for_questions) 

[Matrix ](https://matrix.to/#/#aeon:opensuse.org) 
[Telegram ](https://t.me/openSUSE_Aeon) 
[Discord ](https://discord.gg/opensuse)

**Comment by aylamz** [comment]
> where in I was able to successfully use Login Manager Flatpak to configure GDM on Fedora Silverblue but

I'm using Silverblue but applying settings doesn't work me. Fails with: ```cp: cannot create regular file '/usr/share/gnome-shell/gnome-shell-theme.gresource.default': Read-only file system```

**Comment by Raul1198** [comment]
> > where in I was able to successfully use Login Manager Flatpak to configure GDM on Fedora Silverblue but
> 
> I'm using Silverblue but applying settings doesn't work me. Fails with: `cp: cannot create regular file '/usr/share/gnome-shell/gnome-shell-theme.gresource.default': Read-only file system`

It's was silverblue 38 on Gnome Box , something might have changed in 39

**Comment by realmazharhussain** [comment]
https://github.com/PRATAP-KUMAR/gdm-extension also exists now. I have not tested it myself. If it works, it could be a viable alternative to GDM Settings for immutable distro users.

**Comment by rugk** [comment]
I can confirm this is broken with Fedora SIlverblue 39:

Here I just open it and click apply without changing anything and that fails:
```
$ flatpak run io.github.realmazharhussain.GdmSettings -vvv

(process:2): Gtk-WARNING **: 02:27:01.399: Locale not supported by C library.
	Using the fallback 'C' locale.
INFO:gdms.gui: Application Version    = 4.1
INFO:gdms.gui: Operating System       = Fedora Linux 39.20231223.0 (Silverblue)
INFO:gdms.gui: PackageType            = Flatpak
INFO:gdms.gui: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO:gdms.gui: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO:gdms.gui: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO:gdms.gui: UbuntuGdmGresourceFile = None
INFO:gdms.gui: Default Gresource File = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO:gdms.gui: pkexec version 123
INFO:gdms.settings: Backing up default shell theme …
cp: reguläre Datei '/usr/share/gnome-shell/gnome-shell-theme.gresource.default' kann nicht angelegt werden: Das Dateisystem ist nur lesbar
```

(translated: the file system of '/usr/share/gnome-shell/gnome-shell-theme.gresource.default' is read-only – which makes sense, it is supposed to be in Silverblue)

Maybe a better error message/"X is unsupported" message could be displayed at least?
Or of course be made workign…

ref https://github.com/gdm-settings/gdm-settings/issues/199 (for people searching)

**Comment by realmazharhussain** [comment]
> Maybe a better error message/"X is unsupported" message could be displayed at least?
Or of course be made working…

I have opened an issue tracker for that now. https://github.com/gdm-settings/gdm-settings/issues/227

**Comment by realmazharhussain** [comment]
I have installed GNOME OS in GNOME Boxes. It (and consequently, any other Systemd-based immutable/image-based distros) may get supported in the future. That is why I have re-opened this issue tracker.

**Comment by TheRsKing** [comment]
> I have installed GNOME OS in GNOME Boxes. It (and consequently, any other Systemd-based immutable/image-based distros) may get supported in the future. That is why I have re-opened this issue tracker.

any updates on this?

**Comment by realmazharhussain** [comment]
@TheRsKing
> > I have installed GNOME OS in GNOME Boxes. It (and consequently, any other Systemd-based immutable/image-based distros) may get supported in the future. That is why I have re-opened this issue tracker.
> 
> any updates on this?

Sorry, got busy with stuff.
