### ISSUE TITLE
Custom image for lockscreen

### ISSUE THREAD

**Issue by technout** [gdm-settings/gdm-settings#173]
### Description

Is it possible to set a custom image for the lockscreen as well? Because the gdm login screen is something different.
The current lockscreen is a very blurry image of the desktop image (default).

**Comment by realmazharhussain** [comment]
Sorry, gdm-settings is only meant to change settings for the login manager. There might be other solutions out there. Maybe try searching for an extension or manually edit GNOME Shell CSS.
