### ISSUE TITLE
Background image not spanning both monitors

### ISSUE THREAD

**Issue by MrPestle** [gdm-settings/gdm-settings#175]
### What happened?

I have my background image spanning two monitors. This worked well with a wide .jpg image.
Since the last two or three updates the image is not spanning the full width of the two monitors. I get  the left half of the jpeg on the left monitor and then the whole image across one and a half monitors!

### Expected behavior

The background image should appear spanning across both monitors as a single image

### To Reproduce

Choose a wide background image the width of your two monitors.  Apply the change. logout and login in again.

### Application Version

3.2

### Format/Source

Flatpak

### Environment

- **OS**: 
- **GNOME**: 
Manjaro Linux (up-to-date rolling build)
Gnome 44.3
Kernel Linux 6.1.41-1-Manjaro
Wayland windowing system

**Comment by realmazharhussain** [comment]
Can you share a picture of the login screen?

**Comment by MrPestle** [comment]
![my-manjaro-wide](https://github.com/gdm-settings/gdm-settings/assets/38005274/9ca68145-e93a-4426-bc5b-49fadd6a7c48)
![spanned screens](https://github.com/gdm-settings/gdm-settings/assets/38005274/e31d5f58-16b1-4134-b836-3d8b5974e736)
I enclose the background jpeg and the result on the screens

**Comment by realmazharhussain** [comment]
## Current speculation

In GNOME 44, the login screen has two elements where one is displayed on top of the other. In GDM Settings 3.2, we change background image of both elements to the image user selects. In single display configuration, the element on top completely hides the element behind it. So, the background image seems to be set correctly. It seems like that is not the case here. See https://github.com/gdm-settings/gdm-settings/issues/158 for more info.

## Fix

We could try and set background of the top element to `transparent`. Try [this flatpak][gdm-settings.flatpak.zip] and tell me if it works.

NOTE: Make sure to run it with `flatpak run io.github.realmazharhussain.GdmSettings//master`.

[gdm-settings.flatpak.zip]: https://github.com/gdm-settings/gdm-settings/files/12326731/gdm-settings.flatpak.zip

**Comment by MrPestle** [comment]
Thank you very much - your solution worked perfectly!
