### ISSUE TITLE
Can't open About dialog window on 3.3

### ISSUE THREAD

**Issue by Nilvus** [gdm-settings/gdm-settings#177]
### What happened?

I just tried to open (tried multiple times) About dialog window on 3.3 and gdm setting just freeze or crash. I remember it was working on 3.2.

### Expected behavior

About dialog window should just open!

### To Reproduce

On Gdm-settings, just click on hamburger menu then About and see freeze.

### Application Version

3.3

### Format/Source

Debian Sid package

### Environment

- **OS**:  Debian Sid
- **GNOME**: Gnome 44.3 on Xorg

**Comment by Nilvus** [comment]
I can open it other Gtk4 apps. It works on all Gnome 44.3 or 45 apps I have (Agenda, Contacts, Calculator, Nautilus...). Freeze is only on GDM settings. A minor bug of course!

**Comment by Nilvus** [comment]
Yep, when I launch darktable from a terminal, I first see multiple times:

`(gdm-settings:20625): Gtk-WARNING **: 18:31:52.476: GtkImage 0x22a7630 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.`

And when I click on About link in hamburger menu, terminal reports:

```
/usr/lib/python3/dist-packages/gdm_settings/about.py:49: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  self.store = ASG.Store()
Erreur de segmentation
```

As I install gdm settings from Debian sid repository, could this means a missing Python3 package (and if yes which one)  or an error in code source?

**Comment by Nilvus** [comment]
Just a precision, when I have Python error reported in last comment, gdm settings crash when clicking on About link. Most of the times, gdm setting freeze and nothing is reported on terminal.

**Comment by realmazharhussain** [comment]
It seems like there is a bug in either appstream-glib or pygobject. It could also be that appstream-glib or pygobject is not installed/configured properly on your system.

**Comment by Nilvus** [comment]
Ok, thanks for your help and answers. So I suppose opening that dialog window works on your side. I so close as it's upstream bug.
