### ISSUE TITLE
GTK Hash Mismatch

### ISSUE THREAD

**Issue by IronFractal** [gdm-settings/gdm-settings#178]
### What happened?

gdm-settings won't build due to a hash mismatch for gtk-4.10.4.tar.xz. 

### Expected behavior

Should not fail with the following error:

```
Run-time dependency gtk4 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency gtk4
Downloading gtk source from https://download.gnome.org/sources/gtk/4.10/gtk-4.10.4.tar.xz
Downloading: 100%|██████████████████████████████| 20526652/20526652 [00:06<00:00, 3272476.15bytes/s]
A fallback URL could be specified using source_fallback_url key in the wrap file

meson.build:22:0: ERROR: Incorrect hash for source:
 ebab989b60a5dd36222dccdeecef3e139c1f043f81b1d81e4728a208237f7e4d expected
 7725400482e0685e28265e226c62847f4e73cfca9e9b416ac5838207f5377a24 actual.
```

### To Reproduce

```
git clone --depth=1 https://github.com/gdm-settings/gdm-settings
cd gdm-settings
meson setup build
```

### Detailed Explanation (Optional)

Looks like the latest in the PopOs repos is

libgtk-4-dev:amd64 (4.6.9+ds-0ubuntu0.22.04.1)

### Application Version

d2f17a79882120303bf284df75ac998a15889e5f (commit)

### Format/Source

Source

### Environment

- **OS**: 
- OS: Pop!_OS 22.04 LTS x86_64 

- **GNOME**: 
- DE: GNOME 42.5

**Comment by IronFractal** [comment]
Looks like same story with libadwaita.

Where did you get these hashes?? Because they do not appear to match the sha256 from https://download.gnome.org/sources/

**Comment by realmazharhussain** [comment]
If I remember correctly I got them from download.gnome.org. Either the archives on download.gnome.org were replaced due to some reason or somehow I managed to get both of these hashes wrong.

Anyway, sorry for the inconvenience. I have updated both GTK and LibAdwaita subprojects to their latest version now, with the correct hashes this time.
