### ISSUE TITLE
Does not detect GDM on NixOS - Flatpak install

### ISSUE THREAD

**Issue by jaafar-alawieh** [gdm-settings/gdm-settings#181]
### What happened?

I installed GDM via Flatpak but as far as I understand this would still happen regardless of where I downloaded it from because things are stored differently in NixOS.
It shows me I'm missing GDM as a dependency even though I'm running Gnome + GDM out of the box.
Screenshot Attached below.

### Expected behavior

Supposed to run and let me make my login screen look cool :'(

### To Reproduce

On NixOS,
enable flatpak service
install GDM Manager via flatpak
run the app
It gives the error.

### Detailed Explanation (Optional)
For reference: 
I already used Flatseal to give the application all permissions.
![image](https://github.com/gdm-settings/gdm-settings/assets/85218691/a5a53e87-39e7-4d88-b533-d0f8e8a396e6)

### Application Version

3.3

### Format/Source

Flatpak

### Environment

- **OS**: NixOS 23.05
- **GNOME**: 44.2

**Comment by realmazharhussain** [comment]
Currently, NixOS is not supported. The app cannot work on NixOS because of how NixOS works. For more details read discussion https://github.com/gdm-settings/gdm-settings/discussions/179.
