### ISSUE TITLE
Flathub User Repo and Immutable Distro

### ISSUE THREAD

**Issue by TheRsKing** [gdm-settings/gdm-settings#187]
### What happened?

So first of all, when I'm on a normal distribution with the flathub user repository, the "Apply" button doesn't work (it doesn't even come up with an authentication window). In addition, with opensuse Aeon I can't transfer the display settings and then I get an error message. And since opensuse Aeon uses the user repository, the apply button doesn't work either. And I think even if it did work, the authentication would not work because it does not work with the display settings either.

Edit: I don't think openSUSE Aeon is the problem for authentication, because black box works wonderfully, even sudo commands

### Expected behavior

normal functionality 

### To Reproduce

Install opensuse aeon or use the flatpak user repository (on normal distributions with the flatpak user repository the authentication works, only the apply button does not)

### Application Version

3.3

### Format/Source

Flatpak (User)

### Environment

- **Opensuse Aeon /& Tumbleweed with User Repository**: 
- **GNOME 45**:

**Comment by realmazharhussain** [comment]
I tested a user install of the app on my Arch Linux system and it worked as intended.

Can you run it from the terminal and provide the output it generates here?

**Comment by TheRsKing** [comment]
Oh, i'm stupid, 3.3 isn't compatible with gnome 45 at all.

**Comment by TheRsKing** [comment]
I think now its only the "normal" immutable distro Problem
