### ISSUE TITLE
Activity symbols in Gnome 45 on the top left corner get removed.

### ISSUE THREAD

**Issue by ilikelinux69** [gdm-settings/gdm-settings#190]
### What happened?

I lost the Activity symbols in Gnome 45 on the top left corner.

### Expected behavior

The symbols should not disappear. 

### To Reproduce

Using gdm-settings 3.3 on Gnome 4.5

The workaround to fix is for the moment, to reinstall gnome-shell package and re-login or reboot.

### Detailed Explanation (Optional)

I saved settings I made in F38 in the new Beta version of Fedora39 (I upgraded) and lost the new activities symbols Gnome 45 uses.

Please see here for more details:
[discussion.fedoraproject.org](https://discussion.fedoraproject.org/t/activity-symbols-how-to-display-them-again-after-using-the-login-manager-settings/91691)

### Application Version

Gnome 45 and LoginManagerSettings 3.3

### Format/Source

Flatpak from Flathub

### Environment

- **OS: Fedora 39**: 
- **GNOME: 45**:

**Comment by realmazharhussain** [comment]
Are you using a custom shell theme or *Default*?

**Comment by ilikelinux69** [comment]
In Gnome-Tweaks the default seams to be empty at "Appearance > Shell > ( ! Shell user-theme not enabled)
Cursor & Icons is Adwaita (default) and Legacy Applications are Adwaita-dark

And in Settings > Appearance I have selected the dark theme.

Installed Packages: (sudo dnf list *theme*)

adwaita-cursor-theme.noarch                      45.0-1.fc39         @System        
adwaita-gtk2-theme.x86_64                       3.28-17.fc39         @fedora        
adwaita-icon-theme.noarch                          45.0-1.fc39         @System        
clearlooks-compact-gnome-theme.noarch1.5-26.fc39         @fedora        
gnome-icon-theme.noarch                      3.12.0-20.fc39         @fedora        
gnome-themes-extra.x86_64                      3.28-17.fc39        @fedora        
hicolor-icon-theme.noarch                          0.17-16.fc39        @fedora        
highcontrast-icon-theme.noarch               3.28-17.fc39        @fedora        
plymouth-system-theme.x86_64        22.02.122-5.fc39        @fedora        
plymouth-theme-spinner.x86_64        22.02.122-5.fc39        @fedora        
sound-theme-freedesktop.noarch               0.8-20.fc39        @fedora

**Comment by realmazharhussain** [comment]
I meant in Login Manager Settings.

![Screenshot from 2023-10-08 12-05-44](https://github.com/gdm-settings/gdm-settings/assets/67191572/982b9d01-acea-4ccf-a687-c329ed5a101c)

**Comment by realmazharhussain** [comment]
Also, I forgot to mention. Login Manager Settings version 3.3 does not support GNOME 45. Use [the beta version](https://dl.flathub.org/beta-repo/appstream/io.github.realmazharhussain.GdmSettings.flatpakref) instead.

**Comment by ilikelinux69** [comment]
I think the name changed from Activities to Workspace Indicator and it is made with an extension ?!

https://ubuntuhandbook.org/index.php/2023/09/activities-replaced-workspace-indicator-gnome/

**Comment by realmazharhussain** [comment]
> I think the name changed from Activities to Workspace Indicator

Yeah, that shouldn't matter. I don't know what is happening here.

To workaround this issue, reinstall `gnome-shell` package.
