### ISSUE TITLE
User login panel colour goes blue

### ISSUE THREAD

**Issue by MrPestle** [gdm-settings/gdm-settings#191]
### What happened?

You kindly sent me a link to a  flatpak version to overcome the two screen display problem but now when I login it displays the green panel I expect but when I mouse over a user it turns blue, with sometimes a flash of the green panel.

https://github.com/gdm-settings/gdm-settings/assets/38005274/776a658d-d8ca-4859-bf86-07fe50c57a5b

### Expected behavior

Selecting a user the panel remains green - (in some shade or other!)

### To Reproduce

Boot system and login as a user

### Application Version

3.3

### Format/Source

Flatpak

### Environment

- **OS**:  Manjaro Linux
- **GNOME**:  44.5

**Comment by realmazharhussain** [comment]
Are you using `gnome-shell` or `gnome-shell-maia` package? And what shell theme did you choose in the app?

**Comment by MrPestle** [comment]
Thank you - your question pointed me in the right direction - I switched to gnome-shell-maia and it now works as expected.
Great support - great program

**Comment by yochananmarqos** [comment]
@MrPestle FYI, `gnome-shell-maia` is now deprecated and has nothing to do with GDM Settings.

@realmazharhussain I didn't think GDM Settings was able to change the GDM accent color. Did I miss something?

**Comment by realmazharhussain** [comment]
@yochananmarqos No, you didn't miss anything. GDM Settings itself does not have the feature of changing accent color. However, it can apply themes like Maia which only seem to differ from the default theme in the accent color they have.
