### ISSUE TITLE
Gnome 45. Unable to apply a image background F39 Dual wide screen monitor

### ISSUE THREAD

**Issue by jspurrier** [gdm-settings/gdm-settings#192]
### What happened?

Gnome 45. Unable to apply a image background F39 Dual wide screen monitor.  When selecting image from drop downs it fills as expected but when you hit apply it doesnt really do anything. Closing and reopening it simply resets it back to the default settings

### Expected behavior

Should save the change and apply image as background

### To Reproduce

Gnome 45 Appearance -> Image -> change from default to file. Select file. Click apply. 

### Application Version

3.3

### Format/Source

Flatpak

### Environment

- **OS**: Fedora 
- **GNOME **: 45

**Comment by realmazharhussain** [comment]
GDM Settings 3.3 was released long before GNOME 45 and does not support it. Use the beta version.
