### ISSUE TITLE
AppImage and Flatpak Do Not Open on Pop OS 22.04

### ISSUE THREAD

**Issue by ShiromMakkad** [gdm-settings/gdm-settings#193]
### What happened?

I tried installing this application from Flathub and through the AppImage but neither launched

I tried running 

`./Login_Manager_Settings.AppImage`

and got:

```
(AppImageLauncher:10795): GLib-CRITICAL **: 00:05:48.052: g_file_test: assertion 'filename != NULL' failed
/tmp/.mount_Login_6fP9Xv/AppRun: line 8: 10845 Segmentation fault      (core dumped) gdm-settings "$@"

```
I don't think the issue is with AppImageLauncher despite the error line because it showed the error, then AppImageLauncher properly opened its prompt, I selected run once and it then crashed and emitted the second log line. 

### Expected behavior

It should've opened

### To Reproduce

Run the program on PopOs 22.04

### Application Version

3.3 and v4.beta1

### Format/Source

AppImage and Flatpak

### Environment

- **OS**: 
- PopOS 22.04
- **GNOME**: 
Gnome 45

**Comment by realmazharhussain** [comment]
Yeah, the AppImage does that sometimes. What error does the flatpak emit?

**Comment by ShiromMakkad** [comment]
I was able to fix this by running the beta version in Flatpak. Using the AppImage still doesn't work, nor does version 3.3 on either of them
