### ISSUE TITLE
Changing back to the defaults broke GDM

### ISSUE THREAD

**Issue by vicho-bustos** [gdm-settings/gdm-settings#194]
### What happened?

I changed the settings back to default and it broke GDM, ie, I got the "an error has occured" white screen when i booted up my pc

### Expected behavior

The gdm settings should go back to the defaults

### To Reproduce

Change back to the default settings from a customized login screen. Particularly a different wallpaper and fonts

### Application Version

3.3

### Format/Source

Flatpak

### Environment

- **OS**: Ubuntu 23.04
- **GNOME**: 44.3

**Comment by realmazharhussain** [comment]
To work around this issue reinstall `gnome-shell-common` package.

```bash
sudo apt reinstall gnome-shell-common
```
