### ISSUE TITLE
Doesn't apply changes

### ISSUE THREAD

**Issue by alesandu** [gdm-settings/gdm-settings#195]
### What happened?

Apply button doesn't save changes

### Expected behavior

The apply button should work

### To Reproduce

Just install it on Gnome 45.0 

### Detailed Explanation (Optional)

I recently installed gdm-settings, when i click Apply button and than refresh the app CTRL+R, or reopen the login manger, the Apply button doesn't save the changes done

### Application Version

3.3

### Format/Source

gdm-setting

### Environment

- **OS**: EndeavourOS
- **GNOME**: 45.0

**Comment by realmazharhussain** [comment]
GDM Settings v3.3 does not support GNOME 45. Use the latest beta version (currently v4.beta1).
