### ISSUE TITLE
cp: cannot create regular file '/usr/share/gnome-shell/gnome-shell-theme.gresource.default': Read-only file system on Fedora Silverblue

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [gdm-settings/gdm-settings#206]
### What happened?

When I click apply it says "Failed to apply settings"

### Expected behavior

It should work like it does on Fedora Workstation

### To Reproduce

1. Install Fedora Silverblue.
2.  Install GDM Settings through Software app. 
3. Open the app and click apply.

### Detailed Explanation (Optional)

```
08:56:04 rajas@jinlon-fedora ~ → flatpak run io.github.realmazharhussain.GdmSettings -v
INFO:gdms.gui: Application Version    = 4.1
INFO:gdms.gui: Operating System       = Fedora Linux 38.20231103.0 (Silverblue)
INFO:gdms.gui: PackageType            = Flatpak
INFO:gdms.gui: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO:gdms.gui: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO:gdms.gui: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO:gdms.gui: UbuntuGdmGresourceFile = None
INFO:gdms.gui: Default Gresource File = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO:gdms.gui: pkexec version 122
INFO:gdms.settings: Backing up default shell theme …
cp: cannot create regular file '/usr/share/gnome-shell/gnome-shell-theme.gresource.default': Read-only file system
```

### Application Version

4.1

### Format/Source

Flatpak

### Environment

- **OS**:  Fedora Linux 38.20231103.0 (Silverblue)
- **GNOME**: 44.6

**Comment by realmazharhussain** [comment]
As the output says, "Read-only file system". This is a limitation of immutable distributions. To circumvent this issue you can

1. Temporarily mark your `/usr` directory as mutable
2. Apply GDM Settings
3. Change `/usr` back to being immutable

Consult Silverblue's wiki/help for how to make `/usr` mutable on Silverblue.

**Comment by ChocolateLoverRaj** [comment]
What if the app just didn't try to modify `/usr` on Fedora Immutable distros?

**Comment by realmazharhussain** [comment]
Then the app wouldn't work as intended. The app wouldn't modify anything in `/usr` if it didn't need to. Some of the very important features (e.g. Background, Shell Theme, etc.) work by modifying `/usr/share/gnome-shell/gnome-shell-theme.gresource`.

**Comment by ChocolateLoverRaj** [comment]
On Fedora Silverblue the `/usr` dir can be "modified" by overlaying files with `systemd-sysext`. I think GDM Settings should do that.

**Comment by ChocolateLoverRaj** [comment]
@realmazharhussain if Fedora Silverblue is not currently supported then I would be interested in tweaking this to work with Fedora Silverblue. Are there instructions for developing the app?

**Comment by realmazharhussain** [comment]
> On Fedora Silverblue the `/usr` dir can be "modified" by overlaying files with `systemd-sysext`. I think GDM Settings should do that.

Reading the man page, it seems like systemd-sysext creates temporary overlays and won't work.

> if Fedora Silverblue is not currently supported then I would be interested in tweaking this to work with Fedora Silverblue.

GDM Settings is an app that modifies the system. Modifying the system and immutability are inherently incompatible concepts. Even when possible, these two concepts should not be mixed.

Additionally, GDM is not customizable. GDM Settings uses hacks to customize GDM. If it supported an immutable distro, we will be putting a hack on top of a hack. That's double the points of possible failures.

For example, in normal distros, `gnome-shell-theme.gresource` file gets overwritten on each gnome-shell update. GDM Settings can detect that and backs it up. Then in the future, it uses the backed up original file as a base to put modifications on top of. But it can't detect a new installation of the `gnome-shell-theme.gresource` in immutable distros as the file generated by GDM Settings would be overlayed on top of that file, hiding it completely. In that case, a major GNOME Shell update would most likely completely break the visuals (and as a result of that, functionality would also be broken).

So, the official distribution of GDM Settings will not support immutable distros (e.g. Silverblue). However, if you are able to make GDM Settings work with Silverblue, you can maintain a Silverblue-specific port of the app.

> Are there instructions for developing the app?

Sadly, I haven't gotten to that part yet. You can ask questions though.

The basic structure of the repo is as below.
* `/gdms`: Contains all the python code
  * `/gdms/__init__.py`: Contains all the initialization code and `main()`
  * `/gdms/*.py`: Contain base/backend of the app
  * `/gdms/gui/`: Contains GUI definitions/logic
  * `/gdms/gui/__init__.py`: Contains `GdmSettingsApp` class (subclass of `Adw.Application`)
* `/resources`: Contains the resources (including UI blueprints) required by the app
* `/data`: Contains data e.g. app icons, gsettings schemas, .desktop file, etc.

The app uses standard GNOME tooling/libraries. So, [Meson](https://mesonbuild.com), [PyGObject](https://pygobject.readthedocs.io), [LibAdwaita](https://gnome.pages.gitlab.gnome.org/libadwaita), [GTK](https://gtk.org), [Blueprint](https://jwestman.pages.gitlab.gnome.org/blueprint-compiler), etc.

**Comment by ChocolateLoverRaj** [comment]
> Reading the man page, it seems like systemd-sysext creates temporary overlays and won't work.

The overlays aren't really temporary. Once you create them, they are applied on every reboot until you remove them. From the man page: "where a /usr/ and/or /opt/ hierarchy residing on a read-only file system shall be extended temporarily at runtime without making any persistent modifications". I think it means that the actual `/usr` directory will not be modified on the disk itself. Modifications will only show up when `systemd-sysext merge` is executed and after rebooting, if `systemd-sysext merge` is not executed, the modifications will not show up.

> GDM Settings is an app that modifies the system. Modifying the system and immutability are inherently incompatible 
concepts. Even when possible, these two concepts should not be mixed.

I don't see any disadvantages to using overlays to modify an immutable system. `systemd-sysext` works great with Fedora Silverblue.

> Additionally, GDM is not customizable. GDM Settings uses hacks to customize GDM. If it supported an immutable distro, we will be putting a hack on top of a hack. That's double the points of possible failures.

1. `systemd-sysext` is not a hack
2. The overlay adds a point of failure, but if the overlay fails the worst case is the unmodified GDM screen will be shown, so at least it won't break things. 

> For example, in normal distros, gnome-shell-theme.gresource file gets overwritten on each gnome-shell update. GDM Settings can detect that and backs it up. Then in the future, it uses the backed up original file as a base to put modifications on top of. But it can't detect a new installation of the gnome-shell-theme.gresource in immutable distros as the file generated by GDM Settings would be overlayed on top of that file, hiding it completely. In that case, a major GNOME Shell update would most likely completely break the visuals (and as a result of that, functionality would also be broken).

The backup file can just be placed in a writable place like `/etc` or part of the overlay itself. The backup file just can't be placed in `/usr`.

**Comment by realmazharhussain** [comment]
> The overlays aren't really temporary. Once you create them, they are applied on every reboot until you remove them.

Great.

> I don't see any disadvantages to using overlays to modify an immutable system. systemd-sysext works great with Fedora Silverblue.

systemd-sysext is for users, not random apps modifying the system they thought was immutable behind their back.

> The overlay adds a point of failure, but if the overlay fails the worst case is the unmodified GDM screen will be shown, so at least it won't break things.

Not true. The worst case is the overlay working improperly. It can actually prevent the system from booting.

Although, the damage can most probably be reverted by un-applying the overlay.

> The backup file can just be placed in a writable place like /etc or part of the overlay itself. The backup file just can't be placed in /usr.

The issue is not about the act of saving the backup file. It is about detecting a new installation of the original file and being able to read/copy it.

**Comment by ChocolateLoverRaj** [comment]
I just realized that many customizations can be done like normal on Fedora Silverblue without hacks. Here is the link in case anyone else wants to: https://wiki.archlinux.org/title/GDM#Configuration. With the guide I was able to change scaling, tap-to-click, and logo.
