### ISSUE TITLE
Large .png files overlay the login box and user pic on login screen

### ISSUE THREAD

**Issue by ekithmp** [gdm-settings/gdm-settings#214]
### What happened?

When using a large .png as a -> Login Background.
Rather than loading a background image on the login screen, the image overlays the login box and user pic, leaving them completely obscured.

I was able to log in blindly, but there's no visible action or focus on screen.

Using a smaller image does put it *below* the login box if it's small enough not to rise above the box -- As explicitly stated in the documentation, so there's that.

### Expected behavior

Thought a screen background would be the layer below the active information needed to log into an initial desktop session.

### To Reproduce

Use a large .png picture for the background.

Tried it with Wayland and Xorg.  They both exhibited the same behavior.

### Application Version

V4.1

### Format/Source

AppImage from git

### Environment

OS:   Ubuntu 23.10
GNOME:   45.1 -- Wayland  *and* Xorg

**Comment by realmazharhussain** [comment]
You are most probably using the setting shown below.

![Screenshot from 2023-12-20 17-17-47](https://github.com/gdm-settings/gdm-settings/assets/67191572/e515257e-d3ab-4188-b96b-fbcf8102ed4f)

It is the distro "Logo" not background.

Use the setting shown in the picture below to change the background.

![Screenshot from 2023-12-20 17-14-31](https://github.com/gdm-settings/gdm-settings/assets/67191572/ed0949d0-d575-46dd-ad18-a7d98836f2ff)
