### ISSUE TITLE
Start... Deactivated.

### ISSUE THREAD

**Issue by Jetrom17** [gdm-settings/gdm-settings#215]
### What happened?

From the official website, I downloaded the executable file and errors occurred according to the attached log. It simply won't start.

I tried running it, but it didn't work either:

https://github.com/TheAssassin/AppImageLauncher/tree/v2.2.0

The wiki of other sources such as dependency and manual installation is not clear. In my case KDE. You are not to blame for this.

### Expected behavior

```py
jan 03 08:10:12 jeiel-pc systemd[1708]: Started /home/jeiel/Downloads/appimagelauncher-lite-2.2.0-travis995-0f91801-x86_64.appimage.
jan 03 08:10:13 jeiel-pc systemd[1708]: Reloading.
jan 03 08:10:13 jeiel-pc dolphin[16373]: Error: no option passed, use --help for more information
jan 03 08:10:13 jeiel-pc systemd[1]: tmp-.mount_appimacUXLL3.mount: Deactivated successfully.
jan 03 08:10:32 jeiel-pc dolphin[16387]: /usr/bin/AppImageLauncher: /usr/lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
jan 03 08:10:32 jeiel-pc kwin_x11[2276]: kwin_core: XCB error: 152 (BadDamage), sequence: 21411, resource id: 8509684, major code: 143 (DAMAGE), minor code: 3 (Subtract)
jan 03 08:10:32 jeiel-pc systemd[1708]: Started /home/jeiel/Downloads/appimagelauncher-lite-2.2.0-travis995-0f91801-x86_64.appimage.
jan 03 08:10:32 jeiel-pc systemd[1708]: Reloading.
jan 03 08:10:33 jeiel-pc dolphin[16405]: Error: no option passed, use --help for more information
jan 03 08:10:33 jeiel-pc systemd[1]: tmp-.mount_appimaKFb3en.mount: Deactivated successfully.
```

### To Reproduce

It just doesn't work when I run `AppImage`. 

### Application Version

4.1

### Format/Source

Flatpak, AppImage, Source Code

### Environment

- **OS**: RegataOS.
- **KDE**:  plasmashell 5.27.10.

> All latest versions;

**Comment by realmazharhussain** [comment]
If you uninstall AppImageLauncher, does it work after?
