### ISSUE TITLE
Fractional scaling is not correctly enabled when applying current display settings to GDM

### ISSUE THREAD

**Issue by Isaskar** [gdm-settings/gdm-settings#219]
### What happened?

When clicking "Apply current display settings", with fractional scaling enabled for your user and a fractional scaling value set, fractional scaling does not actually take effect until it is manually enabled for the `gdm` user. 

### Expected behavior

Fractional scaling values taking effect in GDM when clicking "Apply current display settings", enabling fractional scaling for the `gdm`user if necessary.

### To Reproduce

- If fractional scaling is already enabled for the `gdm` user, disable it, with
```
sudo machinectl shell gdm@ /bin/bash
gsettings set org.gnome.mutter experimental-features "[]"
```
- Enable fractional scaling for your own user, with
```
gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
```
- Set a fractional scaling value in the GNOME settings.
- Click "Apply current display settings"
- Log out. Fractional scaling is not applied.
- Manually enable fractional scaling for the `gdm` user, with
```
sudo machinectl shell gdm@ /bin/bash
gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
```
- Log out. Fractional scaling will now work correctly.

### Detailed Explanation (Optional)

My guess after looking at the code is that there is simply a missing comma in the following piece of code:

https://github.com/gdm-settings/gdm-settings/blob/6e8473a8ea5d3ccc672659f63e587b06951dd007/gdms/settings.py#L608-L612

There should be a comma between `'org.gnome.mutter'` and `'experimental-features'`, no?

### Application Version

4.1

### Format/Source

Flatpak

### Environment

- **OS**: Fedora 39
- **GNOME**: 45.2

**Comment by fabcard** [comment]
Hello. Please fix this bug. I have the same problem. I use fractional scale 150% on gnome. I load session settings on GDM-settings and apply, but it's not changing the scale on GDM login screen. Thanks in advance.
