### ISSUE TITLE
Add support for changing the (CSS file) that sets the user list color?  It is alway blue?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [gdm-settings/gdm-settings#230]
### Description

Add support for changing the (CSS file) that sets the user list color?  That would seem to be a clear and obvious feature to add no?    It is always a royal blue color?

### Explanation

Add support for changing the (CSS file) that sets the user list color?  That would seem to be a clear and obvious feature to add no?    It is always a royal blue color?

**Comment by realmazharhussain** [comment]
You can change the shell theme.

**Comment by Jibun-no-Kage** [comment]
Ah... will check that out, thanks.
