### ISSUE TITLE
Add as a dependency in Debian/ubuntu appstream-util

### ISSUE THREAD

**Issue by vadimk1337** [gdm-settings/gdm-settings#232]
### What happened?

the program complained during assembly that there was no appstream-util
need to be added depending sudo apt install appstream-util

### Expected behavior

I would download all the dependencies according to the instructions

### To Reproduce

Download dependencies according to instructions
Compile on Ubuntu

### Application Version

3.3

### Format/Source

Source Code

### Environment

- **OS**: 
- **GNOME**:

**Comment by realmazharhussain** [comment]
`3.3` is an old version. The latest version (`4.3`) does not require `appstream-util`.
