### ISSUE TITLE
Setting large PNGs (250+ MB) as GDM background breaks GNOME Shell

### ISSUE THREAD

**Issue by Myra-Jamison** [gdm-settings/gdm-settings#233]
### What happened?

After changing my GDM background to a .png photo that is 254.4 MB in size, I restarted my machine. Rebooting into my OS hung after successful kernel initialization, while loading the display manager, with no error messages. The OS then white-screened with a "Oh no! Something has gone wrong! Contact your sys admin" graphic. Booting into my OS required using tty, uninstalling `gdm-settings` (`yay -Rs gdm-settings`), and then running `pacman -S gnome-shell` to update the gnome shell. After that, I was able to boot back into gnome. I replicated the issue a couple times, and also checked my `journalctl` logs and found that after making changes in `gdm-settings`, `gnome-shell` indeed fails to start. Changing the GDM background to photos smaller in file size does not cause the issue.

### Expected behavior

I expected the GDM background to change and GDM to boot.

### To Reproduce

In the `gdm-settings` GUI, change the wallpaper to a large .png file (250+ MB) on your system. Press apply, then reboot either using the prompt or your system.

### Detailed Explanation (Optional)

Hardware:

> B450m chipset 
> R5 5600
> RX 6800xt
> 32 GB DDR4
> 1440p monitor
> 1 TB NvME + 4 TB HDD

Thanks for maintaining this package, it is absolutely wonderful and I'll continue to use it--just not with large files as backgrounds :)

### Application Version

gdm-settings 4.3-1

### Format/Source

AUR

### Environment

- **Arch Linux (kernel: Linux 6.8.1-arch1-1)**: 
- **GNOME (45.5, wayland)**:

**Comment by realmazharhussain** [comment]
This issue will now be tracked in #270.
