### ISSUE TITLE
Building GDM Settings on Debian 12

### ISSUE THREAD

**Issue by sakobm** [gdm-settings/gdm-settings#244]
### What happened?

The AppImage doesn't launch on Debian 12

For Cloning repo, dependencies install fine but building fails

### Expected behavior

--

### To Reproduce

--

### Detailed Explanation (Optional)

I tried many of the AppImages but non launch on Debian 12. My system is perfectly configured to handle AppImages. I tried running the AppImage from the terminal and got an error of a missing library which I really can't figure out how to install because there's no clear tutorial online.

For Cloning repo, dependencies install fine but building fails

### Application Version
 AppImage versions don't work Debian 12

### Format/Source

AppImage

### Environment

- **OS**:  Debian 12 
- **GNOME**:  GNOME 43.9

**Comment by sakobm** [comment]
> ### What happened?
> 
> The AppImage doesn't launch on Debian 12
> 
> For Cloning repo, dependencies install fine but building fails
> ### Expected behavior
> 
> --
> ### To Reproduce
> 
> --
> ### Detailed Explanation (Optional)
> 
> I tried many of the AppImages but non launch on Debian 12. My system is perfectly configured to handle AppImages. I tried running the AppImage from the terminal and got an error of a missing library which I really can't figure out how to install because there's no clear tutorial online.
> 
> For Cloning repo, dependencies install fine but building fails
> ### Application Version
> 
> AppImage versions don't work Debian 12
> ### Format/Source
> 
> AppImage
> ### Environment
> 
>     * **OS**:  Debian 12
> 
>     * **GNOME**:  GNOME 43.9

OK so I have found a way out. It turns out some AppImage versions don't work on some distros. After continuous testing I, version 2.1 was able to run on Debian 12 and I was able to customize the login screen to the fullest. You can try version 2.1 if other versions don't launch on your distro. More details found [here](https://sakopc.wordpress.com/2024/05/22/how-to-customize-gdm-and-add-a-wallpaper-using-the-gdm-login-manager-settings-app/).

**Comment by sakobm** [comment]
OK so I have found a way out. It turns out some AppImage versions don't work on some distros. After continuous testing I, version 2.1 was able to run on Debian 12 and I was able to customize the login screen to the fullest. You can try version 2.1 if other versions don't launch on your distro. More details found [here](https://sakopc.wordpress.com/2024/05/22/how-to-customize-gdm-and-add-a-wallpaper-using-the-gdm-login-manager-settings-app/).

**Comment by realmazharhussain** [comment]
The AppImage issue is already known. See #209 for details.

> For Cloning repo, dependencies install fine but building fails

If you would like help on this, please, provide more info.

**Comment by greblosdier** [comment]
I can reproduce the build fail issue on Debian 12.
(Debian 12.5 amd64)

1. `sudo apt install gdm3 policykit-1 libadwaita-1-dev libglib2.0-dev python-gi-dev gettext`
2. `sudo apt install meson gobject-introspection `
3. `git clone --depth=1 https://github.com/gdm-settings/gdm-settings`
4. `cd gdm-settings`
5. `meson setup build`

Fails with:
>subprojects/gtk-4.12.3/meson.build:367:0: ERROR: Dependency 'glib-2.0' is required but not found.

I also noted from the output:
>gtk| Dependency glib-2.0 found: NO found 2.74.6 but need: '>= 2.76.0' (cached)
>Dependency gtk4 found: NO found 4.8.3 but need: '>=4.10'

Meson build log is attached

[meson-log.txt](https://github.com/user-attachments/files/16019579/meson-log.txt)

**Comment by realmazharhussain** [comment]
Debian 12 has old versions of software, e.g. GTK 4.8 rather than 4.10 or higher (current latest is 4.14). The latest version of GDM Settings relies on the latest features of GNOME technologies. Thus, it cannot be built on distros that ship ancient software. If you need the latest GDM Settings, you'll have to use the flatpak. Alternatively, you can use Debian Testing which has gdm-settings in its repos.
