### ISSUE TITLE
Cannot open application on Ubuntu 24.04

### ISSUE THREAD

**Issue by harshil21** [gdm-settings/gdm-settings#245]
### What happened?

I just downloaded the app image just after upgrading to Ubuntu 24.04. However this app image does not open and throws the error:

`/tmp/.mount_GDM_SeU619HU/AppRun: line 8: 17395 Floating point exception(core dumped) gdm-settings "$@"`

I have gnome-tweaks installed as well, does that interfere with this?

### Expected behavior

The application should open.

### To Reproduce

1. Download latest app image (v4.4)
2. Make it executable as a program and run it
3. The above error is shown on the command line.

### Application Version

4.4

### Format/Source

AppImage

### Environment

- **OS**: Ubuntu 24.04
- **GNOME**: 46

**Comment by realmazharhussain** [comment]
This issue is already known. See https://github.com/gdm-settings/gdm-settings/issues/209 for details.
