### ISSUE TITLE
Text is invisible

### ISSUE THREAD

**Issue by Miccio-AN** [gdm-settings/gdm-settings#246]
### What happened?

After last update It looks like this:
![Schermata del 2024-05-23 17-22-43](https://github.com/gdm-settings/gdm-settings/assets/73180185/c1d76597-ef30-43fa-9ed8-1d69d087754e)

### Expected behavior

Normal display

### To Reproduce

Install and run

### Application Version

4.4

### Format/Source

Flatpak

### Environment

- **OS**: Debian 12
- **GNOME**: Gnome 43.9
- driver: nvidia v: 470.223.02
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9

**Comment by realmazharhussain** [comment]
This seems like an NVIDIA issue. Don't other LibAdwaita apps have the same issue? Does this issue occur on Wayland as well?

**Comment by Miccio-AN** [comment]
In another machine with new nVidia driver 525.147.05 (X11) It works perfectly.
For me too, it's a problem that concerns Nvidia, but I wanted to refer to you anyway.
The previous version worked fine.
I haven't done any tests with Wayland (using nVidia ... you know...)
I take this opportunity to thank you for your great work you do with this software. Thank you!

**Comment by realmazharhussain** [comment]
You're welcome.

> The previous version worked fine.

What about other LibAdwaita apps? Do they work just fine?

Does this app output any warning/error on the terminal?

**Comment by Miccio-AN** [comment]
(Excuse my ignorance) How do I know which other apps use LibAdwaita?
As for the terminal, it doesn't show any warnings... 

flatpak run io.github.realmazharhussain.GdmSettings

Tomorrow I'll try to use the Appimage version and tell you what comes out

P.S. Right now I'm using a machine with nVidia [GeForce GT 1030] driver: nvidia v: 525.147.05 and everything works great

**Comment by realmazharhussain** [comment]
> How do I know which other apps use LibAdwaita?

If you are not using a custom theme (e.g. adw-gtk3, Ubuntu's Yaru), You can spot LibAdwaita apps by their style. All LibAdwaita apps I know use a style very similar to each other.

Some GTK apps let you open GTK Inspector via `Ctrl` `Shift` `D` shortcut (LibAdwaita apps are also GTK apps):
1. Open an app
2. Press `Ctrl` `Shift` `D`
3. If a new app (GTK Inspector to be specific) opens, and has an `Adwaita` tab, it means the app you opened in step 1 was a LibAdwaita app.

**Comment by realmazharhussain** [comment]
[Screencast from 2024-05-24 00-39-58.webm](https://github.com/gdm-settings/gdm-settings/assets/67191572/707b31bc-1efd-48fb-9cac-612f2bb167f1)

**Comment by Miccio-AN** [comment]
I did as you asked and installed and checked other apps using LibAdwaita.
I can confirm that they all have the same problem. 
So it's a general bug and not specific to your application. 
Thanks again for your availability.

Sorry if I posted an inappropriate bug!

**Comment by realmazharhussain** [comment]
> Sorry if I posted an inappropriate bug!

Not at all.

<hr>

You can ask on discourse.gnome.org for guidance on where to submit this bug.

**Comment by realmazharhussain** [comment]
Closing this as external bug.
