### ISSUE TITLE
Missing dependency glib2-devel on manjaro

### ISSUE THREAD

**Issue by Korgen1** [gdm-settings/gdm-settings#248]
### What happened?

When trying to install on manjaro with `pamac install gdm-settings`

`Warning: cannot resolve "glib2-devel", a dependency of "gdm-settings"`

### Expected behavior

Successfully install from the AUR

### To Reproduce

Run `pamac install gdm-settings` on manjaro

### Application Version

Latest

### Format/Source

AUR

### Environment

- **OS**:  Manjaro 24.0
- **GNOME**: 46.2

**Comment by realmazharhussain** [comment]
I can't break the app for mainline Arch users, just to cater to Manjaro. A Manjaro update should fix the issue. In the meantime, install `glib2`, and then use `--assume-installed=glib2-devel` flag to force installation of `gdm-settings`.

```sh
paru -S --asdeps --needed glib2
paru -S gdm-settings --assume-installed=glib2-devel
```

Note: `pamac` might not have these flags, or even equivalents (I don't know). So, you might need to use `paru` for this.
