### ISSUE TITLE
Unable to install on Arch via yay

### ISSUE THREAD

**Issue by binarykitchen** [gdm-settings/gdm-settings#249]
### What happened?

The command `yay -S gdm-settings` errors at the end with:
```
 -> error installing repo packages
error installing repo packages
```

### Expected behavior

I expect gdm-settings to be successfully installed.

### To Reproduce

It just happens every time I enter the above command, even after a reboot.

### Detailed Explanation (Optional)

Attached is the complete output when running `yay -S gdm-settings | tee output.txt`
[output.txt](https://github.com/user-attachments/files/16007083/output.txt)

### Application Version

N/A

### Format/Source

yay

### Environment

- **OS**: 6.9.6-arch1-1
- **GNOME**:  46.2

**Comment by realmazharhussain** [comment]
This seems like an issue in your system. Try other AUR helpers, and see if they work.

**Comment by binarykitchen** [comment]
I don't want to install AUR.

How can I investigate this best?

**Comment by realmazharhussain** [comment]
You don't install AUR, you install AUR helpers like `yay`. Just install `paru` and then run `paru -S gdm-settings`.

**Comment by realmazharhussain** [comment]
You can uninstall `paru` afterward. `paru` might give you more information about the error if it is an error in your system. If it is a `yay` bug, the developers of `yay` would be better for helping you diagnose the issue.

**Comment by binarykitchen** [comment]
I ran yay in debug  mode and found this line interesting:
```
returning error 33 from alpm_db_get_pkg (../lib/libalpm/db.c: 316) : could not find or read package
```

Known issue?

**Comment by realmazharhussain** [comment]
It doesn't specify which pacakge?

**Comment by binarykitchen** [comment]
I think it's the gobject-introspection and blueprint-compiler packages it cannot install.

When running `yay -S --debug gdm-settings` I can see the following errors:

```
debug: checkdeps: package gobject-introspection-1.80.1-3
debug: checkdeps: package blueprint-compiler-0.12.0-2
debug: returning error 33 from alpm_db_get_pkg (../lib/libalpm/db.c: 316) : could not find or read package
debug: setting download size 504340 for pkg gobject-introspection
debug: returning error 33 from alpm_db_get_pkg (../lib/libalpm/db.c: 316) : could not find or read package
debug: found cached pkg: /var/cache/pacman/pkg/blueprint-compiler-0.12.0-2-any.pkg.tar.zst
debug: setting download size 0 for pkg blueprint-compiler
debug: sorting by dependencies
debug: started sorting dependencies
debug: sorting dependencies finished
debug: returning error 33 from alpm_db_get_pkg (../lib/libalpm/db.c: 316) : could not find or read package
debug: returning error 33 from alpm_db_get_pkg (../lib/libalpm/db.c: 316) : could not find or read package
```

**Comment by realmazharhussain** [comment]
Run `sudo pacman -Scc` (answer yes to the questions asked) to clean the pacman caches, and then run

```bash
cd ~/.cache/yay/clone/gdm-settings
makepkg -Lfsi
```

See if that provides more info, or fixes the issue.

**Comment by binarykitchen** [comment]
Afraid, this didn't help. But I figured, with `overwrite` it worked.
```bash
sudo pacman -S gobject-introspection --overwrite "*"
```
