### ISSUE TITLE
Not working on Debian testing

### ISSUE THREAD

**Issue by Karolus62** [gdm-settings/gdm-settings#256]
### What happened?

GDM Settings in Debian testing does not show any background image.
I have Gnome Shell 46 on Dell Latitude 7490.
Also Gnome Shell 46 with EndeavourOS on Dell Latitude 5570 and on an assembled desktop pc works fine. I think the bug is about GDM Settings...

### Expected behavior

I would like the procedure for changing the background image to remain the same as in EndeavourOS on Debian as well, but this time it would work

### To Reproduce

I open GDM Settings
Click on "Background", "Image"
I choose an image
Click on "Apply"
the image becomes the background of my GDM

### Application Version

4-4-1

### Format/Source

.deb package

### Environment

- **OS**:  Debian testing ("Trixie")
- **GNOME**:  46

**Comment by Karolus62** [comment]
I noticed that when I go to select the image in the GDM-Settings window, it makes me do all the operations, but when I give the "Apply" command, then I end the session and I restart it, the GDM is always black. If I go and look in GDM-Settings, "Image" is not enabled, even though I had enabled it before and applied the changes I made.

**Comment by realmazharhussain** [comment]
Try installing GDM Settings from source. Does that work?

**Comment by Karolus62** [comment]
Installing from source I had an error (the command wget copied an
empty file). I installed gdm-settings from flatpak and it works fine.
Many thanks

 Il martedì 5 novembre 2024 alle ore 17:23, Mazhar Hussain
***@***.***> ha scritto:
