### ISSUE TITLE
Accent Color Support

### ISSUE THREAD

**Issue by zhaose233** [gdm-settings/gdm-settings#258]
### Description

The new gnome 47 release has added native accent color support, and the value of accent color is stored at /org/gnome/desktop/interface/accent-color as an enum. It will be nice to have accent color support in GDM Settings.

**Comment by nnimoyoefoki** [comment]
This might help:This file might fix it
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by realmazharhussain** [comment]
Try [the beta version](https://dl.flathub.org/beta-repo/appstream/io.github.realmazharhussain.GdmSettings.flatpakref) and see if it works.
