### ISSUE TITLE
After installing gdm-settings, the system experiences noticeable stuttering, delay, or black screen each time logging or locking the screen

### ISSUE THREAD

**Issue by suisbuds** [gdm-settings/gdm-settings#261]
### What happened?

After installing GDM Settings using yay, I configured a custom Mable-yellow-light-Theme and Bibata-Modern-ice-Cursor, and enabled a background image with a size of 14MB. 
However, I noticed that compared to using the native GDM service, every time I lock the screen, enter the password to login, or login after locking the screen, the **system experiences noticeable stuttering and delays**. 
For example, after entering password to login , there will be a black screen lasting several seconds and stuttering before the normal screen appears.

### Expected behavior

The system should not experience noticeable stuttering, delays, or black screens each time it logs in or locks the screen.

### To Reproduce

login or lock the screen on arch linux, and you may see the similar condition.

### Application Version

GDM 47.0

### Format/Source

AUR

### Environment

- **OS**: Arch Linux 
- **GNOME**: 47.0
- **Kernel:** Linux 6.11.2-arch1-1

**Comment by suisbuds** [comment]
> Does using a smaller size background image fix the issue?

yes😂

**Comment by realmazharhussain** [comment]
This issue will now be tracked in #270.
