### ISSUE TITLE
App doesn't launch

### ISSUE THREAD

**Issue by adm1ncooler** [gdm-settings/gdm-settings#262]
### What happened?

`flatpak run io.github.realmazharhussain.GdmSettings`
```
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
```

### Expected behavior

App needs to be launched, but fails.

### To Reproduce

`flatpak run io.github.realmazharhussain.GdmSettings` using Mesa drivers.
Now i can workaround it by executing `GSK_RENDERER=gl flatpak run io.github.realmazharhussain.GdmSettings`.

### Detailed Explanation (Optional)

Check this: https://github.com/tchx84/Flatseal/issues/725

### Application Version

Latest

### Format/Source

Flatpak

### Environment

- **OS**: Fedora Linux 40 (Workstation Edition) x86_64 
- **GNOME**:  46.5

**Comment by realmazharhussain** [comment]
Yeah, it seems to be an issue with GTK new Vulkan renderer, Mesa.

You can probably continue using the new GL render though.

```GSK_RENDERER=ngl```
