### ISSUE TITLE
Background image on Login-screen for multi-monitor with different max resolutions does not work as expected.

### ISSUE THREAD

**Issue by richard378** [gdm-settings/gdm-settings#263]
### What happened?

Version 4.3 on Ubuntu 24.04 LTS. 

 The background setting for image on the lock screen is not able to render correctly. 
 
  I have multiple monitors.  1 1440p and 2 1080p monitors.  My main login screen is the 1440p monitor.  
  
When it is set to fill screen it is distorted to fill one picture for all 3 screens and appears wrong on all of them.  

And when it is set on repeat it fills the 1440p monitor correctly but the other two monitors it is distorted because it tries to render 1440p on the 1080p screens.  

### Expected behavior

It should render the screen size according to each monitor individually on multi monitor setups of different resolutions.  For fill it should render 1 picture per screen of the appropriate resolution for each monitor.  And not span 3 monitors for 1 picture.

### To Reproduce

On multi-monitor system with different max resolution for separate monitors set background image in gdm-settings.

### Application Version

4.3

### Format/Source

Ubuntu apt

### Environment

- **OS**:  Ubuntu 24.04 LTS
- **GNOME**: Version 46 (Default version for Ubuntu) 

**Application Version**: `4.3`  
**Operating System**: `Ubuntu 24.04.1 LTS`  
**Package Type**: `Unknown`  
**TEMP_DIR**: `/run/user/1000/app/io.github.realmazharhussain.GdmSettings`  
**HOST_DATA_DIRS**: `/usr/local/share:/usr/share`  
**Main GResource File**: `/usr/share/gnome-shell/gnome-shell-theme.gresource`  
**Ubuntu GResource File**: `/usr/share/gnome-shell/gdm-theme.gresource`  
**Default GResource File**: `/usr/share/gnome-shell/gnome-shell-theme.gresource.default`

**Comment by realmazharhussain** [comment]
This is a GDM limitation. Nothing I can do about it.
