### ISSUE TITLE
symbol lookup error: /tmp/.mount_GDM_SercdIqA/usr/lib/libc.so.6: undefined symbol: __tunable_is_initialized, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by Zorono** [gdm-settings/gdm-settings#264]
### What happened?

it failed to run on my Ubuntu **22.04.5** due to some kind of **incompatibility** with **libc**

### Expected behavior

it was expected to get opened

### To Reproduce

try to run gdm-settings AppImage on **Ubuntu 22.04.5 LTS**

### Application Version

4.4

### Format/Source

AppImage

### Environment

- **OS**:  Ubuntu 22.04.5
- **GNOME**:  42.9

**Comment by realmazharhussain** [comment]
Duplicate of #209.
