### ISSUE TITLE
After waking up from suspend, the screen back-light brightness is set to maximum

### ISSUE THREAD

**Issue by Hypoths** [gdm-settings/gdm-settings#269]
### What happened?

I'm using gdm-settings for custom wallpaper only on login screen of GDM.When I tried to wake up and login my laptop from suspend status,the screen back-light always change to maximum value until I change the brightness manually.
The following are messages that may be used.

```bash
~ ~> gdm --version                                             
GDM 47.0
~ ~> gnome-shell --version
GNOME Shell 47.1
~ ~> cat /sys/power/mem_sleep
[s2idle]
~ ~> neofetch                                         
                   -`                    cherry@arch 
                  .o+`                   ----------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: WUJIE14XA Standard 
               `+oooooo:                 Kernel: 6.11.6-zen1-1-zen 
               -+oooooo+:                Uptime: 4 hours, 2 mins 
             `/:-:++oooo+:               Packages: 1011 (pacman), 12 (flatpak) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 2880x1800 
          `/+++ooooooooooooo/`           DE: GNOME 47.1 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: WhiteSur-Dark 
       -osssssso.      :ssssssso.        Theme: WhiteSur-Light [GTK2/3] 
      :osssssss/        osssso+++.       Icons: WhiteSur-light [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: kgx 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 7 8845HS w/ Radeon 780M Graphics ( 
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI 65:00.0 Phoenix3 
 `++:.                           `-/+/   Memory: 7081MiB / 23309MiB 
 .`                                 `/

```

### Expected behavior

The back-light brightness value remains at the value it had when the notebook was suspended.

### To Reproduce

Set a custom wallpaper for GDM, suspend the laptop and then wake it up.

### Application Version

GDM Settings 4.4

### Format/Source

AUR(gdm-setting)

### Environment

- **OS**: Arch Linux x86_64 (kernel: 6.11.6-zen1-1-zen)
- **GNOME**: 47.1

**Comment by realmazharhussain** [comment]
This looks like a driver update issue. Are you sure this is a GDM Setfings bug?

**Comment by Hypoths** [comment]
> This looks like a driver update issue. Are you sure this is a GDM Setfings bug?

I'm not sure,but it works fine when I using default GDM themes( without `GDM Settings`)

**Comment by realmazharhussain** [comment]
Does using "Reset Settings" option of GDM Settings fix the issue?

**Comment by Hypoths** [comment]
> Does using "Reset Settings" option of GDM Settings fix the issue?

Yes, after using `Reset Settings` everything worked fine.

**Comment by realmazharhussain** [comment]
Does applying again resurface the issue? If so, please share your `/etc/dconf/db/gdm.d/95-gdm-settings`.

**Comment by Hypoths** [comment]
This issue doesn't seem to occur again with `gdm-settings 5.0`
