### ISSUE TITLE
Flatpak: AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by jordan-bravo** [gdm-settings/gdm-settings#274]
### What happened?

- Program fails to start and shows traceback:
```py
Traceback (most recent call last):
  File "/app/bin/gdm-settings", line 12, in <module>
    status = gdms.main()
             ^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/gdms/__init__.py", line 86, in main
    from .gui import GdmSettingsApp
  File "/app/lib/python3.12/site-packages/gdms/gui/__init__.py", line 18, in <module>
    from gdms import debug_info
  File "/app/lib/python3.12/site-packages/gdms/debug_info.py", line 14, in <module>
    ("Default GResource File", gresource.get_default()),
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/gdms/gresource.py", line 57, in get_default
    if is_unmodified(file):
       ^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/gdms/gresource.py", line 41, in is_unmodified
    if env.HOST_ROOT and not gresourceFile.startswith(env.HOST_ROOT):
                             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Expected behavior

Program should start.

### To Reproduce

- Installed via Flatpak from flathub.org
- Run command: `flatpak run io.github.realmazharhussain.GdmSettings`

### Application Version

4.4

### Format/Source

Flatpak (flathub.org)

### Environment

System details:
OS: NixOS
Architecture: x86_64
Desktop Environment: GNOME 47
Installed via: Flatpak (from flathub.org)

**Comment by europe1453** [comment]
The same error. Just installed the app from Flathub in fresh installed Linux Mint 22 Cinnamon.
Any idea how to get it working?

**Comment by realmazharhussain** [comment]
You can reinstall `gnome-shell-common` package.

**Comment by europe1453** [comment]
Okay, it turned out that gnome-shell-common wasn't installed by default in Mint Cinnamon.
Perhaps you should mark that package as dependence.
Now it seems everything is working

**Comment by realmazharhussain** [comment]
Last time I checked, `gnome-shell-common` was a hard dependency of GDM. GDM won't function without it. You must have an alternative `gnome-shell-common` (e.g. `ubuntu-shell-common`, etc. IDK) already installed.
